# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: $(imageName)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

# Publish the build output
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/bin'
    artifactName: 'build-output'
    publishLocation: 'Container'

- script: |
    pip install urllib3==1.26.15 databricks-cli==0.17.6
    echo -e "$(DATABRICKS_URL)\n$(DatabricksToken)" | databricks configure --token
    databricks clusters list
  displayName: 'Configure Databricks CLI'
  env:
    DATABRICKS_URL: $(DATABRICKS_URL)
    DatabricksToken: $(DatabricksToken)

- script: |
    databricks clusters list
  displayName: 'Test Databricks CLI Connection'
  env:
    DATABRICKS_TOKEN: $(DatabricksToken)

